services:
  droid_nuc:
    image: droid-nuc-fr3:0.18.1
    container_name: droid-nuc-fr3
    network_mode: host
    privileged: true
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      memlock: 102400
    devices:
      - /dev:/dev
    environment:
      ROBOT_TYPE: fr3
      LIBFRANKA_VERSION: "0.13.5"
      NUC_IP: 172.16.0.2
      ROBOT_IP: 172.16.0.1
      LAPTOP_IP: 100.79.65.37
    volumes:
      - ./parameters.py:/app/droid/misc/parameters.py
      - ./conf/franka_hardware.yaml:/app/droid/fairo/polymetis/polymetis/conf/robot_client/franka_hardware.yaml
      - ./conf/franka_panda.yaml:/app/droid/fairo/polymetis/polymetis/conf/robot_model/franka_panda.yaml
    restart: unless-stopped
